package main

import (
	"context"
	"log/slog"
	"math/rand"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"github.com/labib0x9/short/config"
	"github.com/labib0x9/short/internal/infra/postgres"
	"github.com/labib0x9/short/internal/infra/rabbitmq"
	"github.com/labib0x9/short/internal/infra/redis"
	"github.com/labib0x9/short/internal/port/queue"
	"github.com/labib0x9/short/internal/worker"

	urlapp "github.com/labib0x9/short/internal/app/url"
	redis_cache "github.com/labib0x9/short/internal/infra/redis/cache"
	"github.com/projectdiscovery/useragent"
)

var urls = []string{
	"https://go.dev",
	"https://go.dev/doc/",
	"https://go.dev/blog/",
	"https://pkg.go.dev",
	"https://go.dev/tour/",
	"https://github.com",
	"https://github.com/golang/go",
	"https://gitlab.com",
	"https://www.wikipedia.org",
	"https://en.wikipedia.org/wiki/Go_(programming_language)",
	"https://www.rust-lang.org",
	"https://www.python.org",
	"https://nodejs.org",
	"https://www.typescriptlang.org",
	"https://kubernetes.io",
	"https://www.docker.com",
	"https://www.postgresql.org",
	"https://redis.io",
	"https://kafka.apache.org",
	"https://www.mysql.com",
	"https://www.sqlite.org",
	"https://www.mongodb.com",
	"https://nginx.org",
	"https://www.kernel.org",
	"https://www.gnu.org",
	"https://www.debian.org",
	"https://ubuntu.com",
	"https://archlinux.org",
	"https://www.freebsd.org",
	"https://www.openbsd.org",
	"https://news.ycombinator.com",
	"https://lobste.rs",
	"https://stackoverflow.com",
	"https://www.reddit.com",
	"https://dev.to",
	"https://medium.com",
	"https://codeforces.com",
	"https://atcoder.jp",
	"https://www.codechef.com",
	"https://leetcode.com",
	"https://www.hackerrank.com",
	"https://cses.fi",
	"https://cp-algorithms.com",
	"https://open.kattis.com",
	"https://vjudge.net",
	"https://www.spoj.com",
	"https://onlinejudge.org",
	"https://projecteuler.net",
	"https://www.topcoder.com",
	"https://www.hackerearth.com",
	"https://www.mozilla.org",
	"https://developer.mozilla.org",
	"https://www.w3.org",
	"https://www.ietf.org",
	"https://datatracker.ietf.org/doc/html/rfc9110",
	"https://www.rfc-editor.org",
	"https://www.cloudflare.com",
	"https://vercel.com",
	"https://www.netlify.com",
	"https://railway.app",
	"https://fly.io",
	"https://www.heroku.com",
	"https://aws.amazon.com",
	"https://cloud.google.com",
	"https://azure.microsoft.com",
	"https://www.digitalocean.com",
	"https://www.linode.com",
	"https://www.hetzner.com",
	"https://grafana.com",
	"https://prometheus.io",
	"https://opentelemetry.io",
	"https://www.elastic.co",
	"https://www.rabbitmq.com",
	"https://nats.io",
	"https://grpc.io",
	"https://protobuf.dev",
	"https://graphql.org",
	"https://swagger.io",
	"https://www.openapis.org",
	"https://jwt.io",
	"https://nextjs.org",
	"https://react.dev",
	"https://vuejs.org",
	"https://svelte.dev",
	"https://tailwindcss.com",
	"https://strapi.io",
	"https://www.anthropic.com",
	"https://claude.ai",
	"https://www.google.com",
	"https://www.bing.com",
	"https://duckduckgo.com",
	"https://www.apple.com",
	"https://www.microsoft.com",
	"https://www.ibm.com",
	"https://www.oracle.com",
	"https://www.jetbrains.com",
	"https://code.visualstudio.com",
	"https://neovim.io",
	"https://www.vim.org",
	"https://www.bracu.ac.bd",
	"https://www.java.com",
	"https://kotlinlang.org",
	"https://www.scala-lang.org",
	"https://www.haskell.org",
	"https://elixir-lang.org",
	"https://www.erlang.org",
	"https://clojure.org",
	"https://www.ruby-lang.org",
	"https://www.php.net",
	"https://www.perl.org",
	"https://www.lua.org",
	"https://julialang.org",
	"https://www.r-project.org",
	"https://dart.dev",
	"https://flutter.dev",
	"https://swift.org",
	"https://ziglang.org",
	"https://nim-lang.org",
	"https://crystal-lang.org",
	"https://ocaml.org",
	"https://www.eclipse.org",
	"https://llvm.org",
	"https://gcc.gnu.org",
	"https://clang.llvm.org",
	"https://cmake.org",
	"https://bazel.build",
	"https://gradle.org",
	"https://maven.apache.org",
	"https://www.npmjs.com",
	"https://yarnpkg.com",
	"https://pnpm.io",
	"https://bun.sh",
	"https://deno.com",
	"https://pypi.org",
	"https://crates.io",
	"https://rubygems.org",
	"https://packagist.org",
	"https://hub.docker.com",
	"https://helm.sh",
	"https://www.terraform.io",
	"https://www.ansible.com",
	"https://www.vagrantup.com",
	"https://www.packer.io",
	"https://www.hashicorp.com",
	"https://www.consul.io",
	"https://www.vaultproject.io",
	"https://nomadproject.io",
	"https://istio.io",
	"https://linkerd.io",
	"https://www.envoyproxy.io",
	"https://traefik.io",
	"https://www.haproxy.org",
	"https://caddyserver.com",
	"https://httpd.apache.org",
	"https://tomcat.apache.org",
	"https://spark.apache.org",
	"https://hadoop.apache.org",
	"https://flink.apache.org",
	"https://airflow.apache.org",
	"https://cassandra.apache.org",
	"https://couchdb.apache.org",
	"https://www.apache.org",
	"https://pulsar.apache.org",
	"https://zookeeper.apache.org",
	"https://lucene.apache.org",
	"https://solr.apache.org",
	"https://camel.apache.org",
	"https://www.influxdata.com",
	"https://www.timescale.com",
	"https://clickhouse.com",
	"https://duckdb.org",
	"https://www.cockroachlabs.com",
	"https://mariadb.org",
	"https://www.percona.com",
	"https://neo4j.com",
	"https://www.scylladb.com",
	"https://etcd.io",
	"https://memcached.org",
	"https://valkey.io",
	"https://www.sqlalchemy.org",
	"https://www.djangoproject.com",
	"https://flask.palletsprojects.com",
	"https://fastapi.tiangolo.com",
	"https://rubyonrails.org",
	"https://laravel.com",
	"https://spring.io",
	"https://expressjs.com",
	"https://nestjs.com",
	"https://gin-gonic.com",
	"https://echo.labstack.com",
	"https://gofiber.io",
	"https://gorm.io",
	"https://sqlc.dev",
	"https://entgo.io",
	"https://cobra.dev",
	"https://github.com/spf13/viper",
	"https://github.com/gin-gonic/gin",
	"https://github.com/gorilla/mux",
	"https://github.com/go-chi/chi",
	"https://github.com/stretchr/testify",
	"https://github.com/jackc/pgx",
	"https://github.com/redis/go-redis",
	"https://github.com/segmentio/kafka-go",
	"https://github.com/uber-go/zap",
	"https://github.com/rs/zerolog",
	"https://github.com/prometheus/client_golang",
	"https://github.com/grpc/grpc-go",
	"https://github.com/golang-migrate/migrate",
	"https://github.com/moby/moby",
	"https://github.com/kubernetes/kubernetes",
	"https://github.com/torvalds/linux",
	"https://github.com/rust-lang/rust",
	"https://github.com/python/cpython",
	"https://github.com/nodejs/node",
	"https://github.com/microsoft/vscode",
	"https://github.com/neovim/neovim",
	"https://github.com/vim/vim",
	"https://github.com/redis/redis",
	"https://github.com/postgres/postgres",
	"https://github.com/git/git",
	"https://github.com/openssl/openssl",
	"https://github.com/curl/curl",
	"https://github.com/nginx/nginx",
	"https://github.com/ggerganov/llama.cpp",
	"https://github.com/facebook/react",
	"https://github.com/vuejs/core",
	"https://github.com/sveltejs/svelte",
	"https://github.com/vercel/next.js",
	"https://github.com/tailwindlabs/tailwindcss",
	"https://github.com/denoland/deno",
	"https://github.com/oven-sh/bun",
	"https://github.com/ziglang/zig",
	"https://github.com/llvm/llvm-project",
	"https://github.com/etcd-io/etcd",
	"https://github.com/prometheus/prometheus",
	"https://github.com/grafana/grafana",
	"https://github.com/hashicorp/terraform",
	"https://github.com/helm/helm",
	"https://github.com/apache/kafka",
	"https://github.com/apache/spark",
	"https://github.com/elastic/elasticsearch",
	"https://github.com/golang/tools",
	"https://github.com/golang/net",
	"https://github.com/golang/sync",
	"https://github.com/protocolbuffers/protobuf",
	"https://github.com/google/uuid",
	"https://github.com/google/go-cmp",
	"https://github.com/spf13/cobra",
	"https://github.com/urfave/cli",
	"https://github.com/charmbracelet/bubbletea",
	"https://github.com/charmbracelet/lipgloss",
	"https://github.com/gorilla/websocket",
	"https://github.com/coder/websocket",
	"https://github.com/creack/pty",
	"https://github.com/docker/docker",
	"https://github.com/containerd/containerd",
	"https://github.com/opencontainers/runc",
	"https://github.com/firecracker-microvm/firecracker",
	"https://github.com/google/gvisor",
	"https://github.com/kubernetes/minikube",
	"https://github.com/kubernetes-sigs/kind",
	"https://github.com/etcd-io/bbolt",
	"https://github.com/dgraph-io/badger",
	"https://github.com/syndtr/goleveldb",
	"https://github.com/google/leveldb",
	"https://github.com/facebook/rocksdb",
	"https://github.com/cockroachdb/cockroach",
	"https://github.com/pingcap/tidb",
	"https://github.com/minio/minio",
	"https://github.com/nats-io/nats-server",
	"https://github.com/rabbitmq/rabbitmq-server",
	"https://github.com/twmb/franz-go",
	"https://github.com/IBM/sarama",
	"https://github.com/hibiken/asynq",
	"https://github.com/riverqueue/river",
	"https://github.com/jmoiron/sqlx",
	"https://github.com/lib/pq",
	"https://github.com/go-sql-driver/mysql",
	"https://github.com/mattn/go-sqlite3",
	"https://github.com/mongodb/mongo-go-driver",
	"https://github.com/uber-go/fx",
	"https://github.com/google/wire",
	"https://github.com/grpc-ecosystem/grpc-gateway",
	"https://github.com/open-telemetry/opentelemetry-go",
	"https://github.com/jaegertracing/jaeger",
	"https://github.com/golangci/golangci-lint",
	"https://github.com/air-verse/air",
	"https://github.com/swaggo/swag",
	"https://github.com/go-playground/validator",
	"https://github.com/golang-jwt/jwt",
	"https://github.com/joho/godotenv",
	"https://github.com/caddyserver/caddy",
	"https://github.com/traefik/traefik",
	"https://github.com/envoyproxy/envoy",
	"https://github.com/istio/istio",
	"https://gobyexample.com",
	"https://go.dev/ref/spec",
	"https://go.dev/ref/mem",
	"https://go.dev/doc/effective_go",
	"https://go.dev/doc/faq",
	"https://go.dev/wiki",
	"https://go.dev/dl/",
	"https://go.dev/play/",
	"https://go.dev/blog/context",
	"https://go.dev/blog/pipelines",
	"https://go.dev/blog/slices-intro",
	"https://go.dev/blog/maps",
	"https://go.dev/blog/defer-panic-and-recover",
	"https://go.dev/blog/error-handling-and-go",
	"https://go.dev/blog/race-detector",
	"https://go.dev/blog/laws-of-reflection",
	"https://go.dev/blog/gos-declaration-syntax",
	"https://go.dev/blog/strings",
	"https://go.dev/blog/json",
	"https://go.dev/blog/profiling-go-programs",
	"https://go.dev/doc/gc-guide",
	"https://go.dev/doc/diagnostics",
	"https://go.dev/doc/tutorial/getting-started",
	"https://go.dev/doc/security/vuln/",
	"https://go.dev/security/",
	"https://go.dev/doc/install",
	"https://go.dev/doc/code",
	"https://pkg.go.dev/net/http",
	"https://pkg.go.dev/context",
	"https://pkg.go.dev/sync",
	"https://pkg.go.dev/sync/atomic",
	"https://pkg.go.dev/database/sql",
	"https://pkg.go.dev/encoding/json",
	"https://pkg.go.dev/os/exec",
	"https://pkg.go.dev/io",
	"https://pkg.go.dev/bufio",
	"https://pkg.go.dev/fmt",
	"https://pkg.go.dev/log/slog",
	"https://pkg.go.dev/testing",
	"https://pkg.go.dev/runtime",
	"https://pkg.go.dev/net",
	"https://pkg.go.dev/time",
	"https://pkg.go.dev/errors",
	"https://pkg.go.dev/strings",
	"https://pkg.go.dev/sort",
	"https://pkg.go.dev/slices",
	"https://pkg.go.dev/maps",
	"https://pkg.go.dev/crypto/sha256",
	"https://pkg.go.dev/os/signal",
	"https://pkg.go.dev/net/http/httptest",
	"https://pkg.go.dev/html/template",
	"https://pkg.go.dev/regexp",
	"https://pkg.go.dev/path/filepath",
	"https://pkg.go.dev/embed",
	"https://pkg.go.dev/golang.org/x/sync/errgroup",
	"https://pkg.go.dev/github.com/jackc/pgx/v5",
	"https://pkg.go.dev/github.com/redis/go-redis/v9",
	"https://www.postgresql.org/docs/",
	"https://www.postgresql.org/docs/current/index.html",
	"https://www.postgresql.org/docs/current/sql-select.html",
	"https://www.postgresql.org/docs/current/indexes.html",
	"https://www.postgresql.org/docs/current/mvcc.html",
	"https://www.postgresql.org/docs/current/using-explain.html",
	"https://redis.io/docs/",
	"https://kafka.apache.org/documentation/",
	"https://kubernetes.io/docs/home/",
	"https://docs.docker.com",
	"https://docs.github.com",
	"https://docs.gitlab.com",
	"https://git-scm.com",
	"https://git-scm.com/book/en/v2",
	"https://man7.org/linux/man-pages/",
	"https://man7.org/tlpi/",
	"https://www.kernel.org/doc/html/latest/",
	"https://www.linuxfromscratch.org",
	"https://wiki.archlinux.org",
	"https://wiki.debian.org",
	"https://tldp.org",
	"https://www.brendangregg.com",
	"https://jvns.ca",
	"https://danluu.com",
	"https://www.joelonsoftware.com",
	"https://martinfowler.com",
	"https://research.swtch.com",
	"https://www.ardanlabs.com/blog/",
	"https://dave.cheney.net",
	"https://eli.thegreenplace.net",
	"https://preshing.com",
	"https://lwn.net",
	"https://www.phoronix.com",
	"https://www.usenix.org",
	"https://dl.acm.org",
	"https://arxiv.org",
	"https://pdos.csail.mit.edu/6.S081/",
	"https://pdos.csail.mit.edu/6.824/",
	"https://ocw.mit.edu",
	"https://www.cs.cmu.edu",
	"https://cs.stanford.edu",
	"https://www.coursera.org",
	"https://www.edx.org",
	"https://www.khanacademy.org",
	"https://www.udemy.com",
	"https://www.freecodecamp.org",
	"https://roadmap.sh",
	"https://www.geeksforgeeks.org",
	"https://www.programiz.com",
	"https://www.w3schools.com",
	"https://www.tutorialspoint.com",
	"https://exercism.org",
	"https://www.codewars.com",
	"https://www.codingame.com",
	"https://adventofcode.com",
	"https://codecrafters.io",
	"https://build-your-own.org",
	"https://neetcode.io",
	"https://codeforces.com/problemset",
	"https://codeforces.com/contests",
	"https://atcoder.jp/contests/",
	"https://leetcode.com/problemset/",
	"https://cses.fi/problemset/",
	"https://usaco.org",
	"https://ioinformatics.org",
	"https://icpc.global",
	"https://www.acm.org",
	"https://www.ieee.org",
	"https://toph.co",
	"https://lightoj.com",
	"https://www.buet.ac.bd",
	"https://www.du.ac.bd",
	"https://www.cuet.ac.bd",
	"https://www.kuet.ac.bd",
	"https://www.ruet.ac.bd",
	"https://www.sust.edu",
	"https://www.northsouth.edu",
	"https://www.iub.edu.bd",
	"https://www.aust.edu",
	"https://www.ewubd.edu",
	"https://www.aiub.edu",
	"https://www.ugc.gov.bd",
	"https://bangladesh.gov.bd",
	"https://www.prothomalo.com",
	"https://www.thedailystar.net",
	"https://www.dhakatribune.com",
	"https://bdnews24.com",
	"https://www.tbsnews.net",
	"https://www.bssnews.net",
	"https://www.banglanews24.com",
	"https://www.jugantor.com",
	"https://www.kalerkantho.com",
	"https://www.ittefaq.com.bd",
	"https://www.bd-pratidin.com",
	"https://www.ntvbd.com",
	"https://www.bkash.com",
	"https://nagad.com.bd",
	"https://www.daraz.com.bd",
	"https://www.pathao.com",
	"https://www.grameenphone.com",
	"https://www.robi.com.bd",
	"https://www.banglalink.net",
	"https://www.btcl.gov.bd",
	"https://www.bb.org.bd",
	"https://www.brac.net",
	"https://www.bracbank.com",
	"https://www.nytimes.com",
	"https://www.bbc.com",
	"https://www.theguardian.com",
	"https://www.reuters.com",
	"https://www.aljazeera.com",
	"https://www.cnn.com",
	"https://www.bloomberg.com",
	"https://www.wired.com",
	"https://arstechnica.com",
	"https://www.theverge.com",
	"https://techcrunch.com",
	"https://www.engadget.com",
	"https://www.zdnet.com",
	"https://www.cnet.com",
	"https://www.infoq.com",
	"https://thenewstack.io",
	"https://www.theregister.com",
	"https://slashdot.org",
	"https://www.nature.com",
	"https://www.science.org",
	"https://www.nasa.gov",
	"https://www.esa.int",
	"https://www.spacex.com",
	"https://www.tesla.com",
	"https://openai.com",
	"https://deepmind.google",
	"https://huggingface.co",
	"https://www.kaggle.com",
	"https://pytorch.org",
	"https://www.tensorflow.org",
	"https://numpy.org",
	"https://pandas.pydata.org",
	"https://scikit-learn.org",
	"https://jupyter.org",
	"https://matplotlib.org",
	"https://opensource.org",
	"https://choosealicense.com",
	"https://creativecommons.org",
	"https://www.eff.org",
	"https://www.fsf.org",
	"https://www.linuxfoundation.org",
	"https://www.cncf.io",
}

func main() {
	testNumber := 1000000

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	cnf := config.GetConfig(".env")

	pgPool := postgres.NewPostgresPool(ctx, cnf.PostgreSQL)
	defer pgPool.Close()

	pgOp := postgres.NewPgxAdapter(pgPool)

	rabbitMq := rabbitmq.NewRabbitMQ(cnf.RabbitMq)
	defer rabbitMq.Close()

	redisClient := redis.Setup(cnf.Redis)
	defer redisClient.Close()

	urlRepo := postgres.NewUrlRepository(pgOp)
	analysisRepo := postgres.NewAnalysisRepository(pgOp)
	cacheRepo := redis_cache.NewCache(redisClient)

	txMngr := postgres.NewTxManager(pgPool)

	urlService := urlapp.NewService(urlRepo, analysisRepo, txMngr, cacheRepo, rabbitMq, cnf)

	worker := worker.NewWorker(rabbitMq, urlService)
	go worker.Run(ctx, "analytics-worker", 10)

	totalAnalytics := 0

	for i := 0; i < testNumber; i += 100 {
		var wg sync.WaitGroup
		for j := 0; j < 100; j++ {
			wg.Add(1)
			go func(ctx context.Context, serial int) {
				defer wg.Done()
				ctxx, cancel := context.WithTimeout(ctx, 10*time.Second)
				defer cancel()

				userAgent := useragent.PickRandom()
				expireAt := time.Now().Add(time.Duration(rand.Intn(24*3600)) * time.Second)

				longUrl := urls[rand.Intn(len(urls))]

				res, err := urlService.Shorten(ctxx, longUrl, &expireAt, userAgent.Raw)
				if err != nil {
					slog.Error("urlService.Shorted()", "error", err)
					return
				}

				for k := 0; k < rand.Intn(120); k++ {
					if totalAnalytics > testNumber {
						break
					}
					ctx, cancel := context.WithTimeout(ctxx, 5*time.Second)
					defer cancel()
					if err := rabbitMq.PublishAnalytics(ctx, queue.ClickEvent{
						ShortCode: res.Code,
						ClickedAt: time.Now(),
						Referer:   "",
						UserAgent: useragent.PickRandom().Raw,
						IP:        "[IP_ADDRESS]",
						Retries:   2,
					}); err != nil {
						slog.Error("Publishing failed", "error", err, "short", res.Code)
						continue
					}
					totalAnalytics++
				}

			}(ctx, j)
			wg.Wait()
		}
	}
}
