CREATE TABLE clicks (
    id  SERIAL PRIMARY KEY,
    url_id   UUID      NOT NULL REFERENCES urls(id) ON DELETE CASCADE,
    referer     VARCHAR(500) NOT NULL DEFAULT '',
    country     VARCHAR(100) NOT NULL DEFAULT '',
    device VARCHAR(50)  NOT NULL DEFAULT '',
    os VARCHAR(50)  NOT NULL DEFAULT '',
    browser VARCHAR(50)  NOT NULL DEFAULT '',
    clicked_at  TIMESTAMP     NOT NULL DEFAULT NOW()
);